title: Crop mapping documentation
description: A starter template for documenting the crop mapping work
theme: just-the-docs


url: https://saralkarki.github.io/croptypemapping


# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template

 