title: Crop mapping documentation
description: A starter template for documenting the crop mapping work
theme: just-the-docs

url: https://just-the-docs.github.io

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template

 